// constants.js
export const projects = [
    {
      id: 1,
      name: "Real time Chat Application",
      description: "A real-time chat app using React, Firebase, and Tailwind CSS. Users can sign in with email and send messages. The app features a responsive design and a clean user interface. User can send messages to any user their conversation is private but it can view them in real-time.",
      techStack: ["React", "FireBase", "Tailwind CSS"],
      githubLink: "https://github.com/ZayanMustafa/ZayChat",
      deployLink: "https://zaychat.vercel.app/",
      youtubeLink: "https://youtu.be/UKUWGNomdOA",
      image: "/Chat.jpeg",
    },
    {
      id: 2,
      name: "Quote Generator",
      description: "A random quote generator that fetches quotes from an MockDataSource. This is a simple project that I made to practice in fetching Data. This project is made using TypeScript.", 
      techStack: ["TypeScript", "Data Fetching", "Bootstrap"],
      githubLink: "https://github.com/ZayanMustafa/QuipQuake-Generator",
      deployLink: "https://zayanmustafa.github.io/QuipQuake-Generator/",
      youtubeLink: "https://youtu.be/lXuQTzXY2jg?si=MUBheWiF0LFjvXv2",
      image: "/Quote.jpeg",
    },
    {
      id: 3,
      name: "Real time Task Tracker",
      description:"A task tracker app that allows users to add and delete tasks. This project was made using React, and Bootstrap.",
      techStack: ["HTML", "CSS", "JavaScript" ,"LocalStorage"],
      githubLink: "https://github.com/ZayanMustafa/TaskTracker",
      deployLink: "https://zayanmustafa.github.io/TaskTracker/",
      youtubeLink: "https://youtu.be/hRBmr_Xv-PY?si=HZRMqZ8BoFkxyuYw",
      image: "/Task.jpeg",
    },
    {
      id: 4,
      name: "Weather App",
      description: "The weather app that fetches the weather data from the OpenWeatherMap API. This project is made using JavaScript, Bootstrap, and API Integration. ", 
      techStack: ["JavaScript", "Bootstrap" , "API Integration" ],
      githubLink: "https://github.com/ZayanMustafa/ClimateTracker",
      deployLink: "https://zayanmustafa.github.io/ClimateTracker/",   
      youtubeLink: "https://youtu.be/YJO50c0ETLU", 
      image: "/Weather.jpeg",
    },
    {
      id: 5,
      name: "Digital Clock",
      description: " A simple digital clock that displays the current time. This project was made using JavaScript, Bootstrap, and Responsive Design and color theme for different size of screen.",
      techStack: ["JavaScript", "Bootstrap", "Responsive Design"],
      githubLink: "https://github.com/ZayanMustafa/DigitalClock",
      deployLink: "https://zayanmustafa.github.io/DigitalClock/",
      youtubeLink: "https://youtu.be/OtVkg36VmDE", 
      image: "/Clock.jpeg",
    },
    {
      id: 6,
      name:"Lock Builder",
      description:"The lock builder that allows users to build their own strong lock. This project was made using JavaScript, Bootstrap, and Responsive Design.",
      techStack: ["JavaScript", "Bootstrap", "Responsive Design"],
      githubLink: "https://github.com/ZayanMustafa/LockBuilder",
      deployLink: "https://zayanmustafa.github.io/LockBuilder/",
      youtubeLink: "https://youtu.be/sWbjCa5PWms", 
      image: "/Lock.jpeg",
    }
      // Add more projects as needed
  ];
